# Generated by Django 4.0.2 on 2022-03-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='release_year',
            field=models.FloatField(default=0),
        ),
    ]
